version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    networks:
      - net-01
    volumes:
      - data:/zookeeper

  kafka:
    build: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.2.183
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - data:/kafka
    networks:
      - net-01

  redis:
    image: redis:4.0.5-alpine
    command: ["redis-server"]
    hostname: redis
    networks:
      - net-01
    volumes:
      - data:/redis

  visitor:
    build: agent
    entrypoint: /sbin/runvisitor.sh
    networks:
      - net-01
    volumes:
      - data:/visitor
      -
  scraper:
    build: agent
    entrypoint: /sbin/runsraper.sh
    networks:
      - net-01
    volumes:
      - data:/scraper

networks:
  net-01:

volumes:
  data:
